# JAVA OPTS
XMX=5g
XMS=4g
DATE = "$(date +%Y%m%d-%H%M%S)"
LOG_DIR = /data/cdw/doris/be/log
JAVA_OPTS_FOR_JDK_17="-Djavax.security.auth.useSubjectCredsOnly=false -Xss2m -Xms$XMS -Xmx$XMX -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=50 -XX:GCPauseIntervalMillis=100 -Xlog:gc*:file=$LOG_DIR/fe.gc.log.$DATE:time,uptime,level,tags:filecount=10,filesize=32M -Dlog4j2.formatMsgNoLookups=true --add-opens java.base/jdk.internal.module=ALL-UNNAMED"

# port
be_port = 9060
brpc_port = 8060
heartbeat_service_port = 9050
webserver_port = 8040

# dir
PID_DIR = /data/cdw/doris/be/pid
UDF_RUNTIME_DIR = /data/cdw/doris/be/lib/udf-runtime
pprof_profile_dir = /data/cdw/doris/be/log
pull_load_task_dir = /data/cdw/doris/be/var/pull_load
scratch_dirs = /tmp
small_file_dir = /data/cdw/doris/be/lib/small_file/
storage_root_path = /data/cdw/doris/be/storage
sys_log_dir = /data/cdw/doris/be/log
user_function_dir = /data/cdw/doris/be/lib/udf
spill_storage_root_path = /data/cdw/doris/be/storage
jeprofile_dir = /data/cdw/doris/be/log
doris_cgroup_cpu_path = /sys/fs/cgroup/cpu/doris

# log
sys_log_level = INFO
sys_log_roll_mode = SIZE-MB-1024
sys_log_roll_num = 100
sys_log_verbose_level = 10
sys_log_verbose_modules =

# download and upload
download_worker_count = 10
upload_worker_count = 10

# clone and compaction
clone_worker_count = 10
max_cumu_compaction_threads = 10
max_base_compaction_threads = 8
max_single_replica_compaction_threads = 5
compaction_task_num_per_disk = 20
compaction_task_num_per_fast_disk = 40
low_priority_compaction_task_num_per_disk = 10
segcompaction_num_threads = 10
cold_data_compaction_thread_num = 5

# load
enable_stream_load_record = true
stream_load_record_batch_size = 2000
streaming_load_json_max_mb = 1024
streaming_load_max_mb = 204800

# cache
enable_file_cache = true

# disk and flush
flush_thread_num_per_store = 30
high_priority_flush_thread_num_per_store = 30
wg_flush_thread_num_per_store = 30
storage_flood_stage_left_capacity_bytes = 10737418240

# others
max_meta_checkpoint_threads = 5
max_tablet_migration_threads = 5
string_type_length_soft_limit_bytes = 16777216

# Default value is 64K, recommended value is 512K or 1M, values above 1M are not recommended.
column_data_page_size = 524288
