SELECT BITMAP_UNION_COUNT(bitmap) FROM (SELECT TO_BITMAP(1) AS bitmap UNION ALL SELECT TO_BITMAP(2) AS bitmap) t;
SELECT BITMAP_COUNT(BITMAP_UNION(bitmap)) FROM (SELECT TO_BITMAP(1) AS bitmap UNION ALL SELECT TO_BITMAP(2) AS bitmap) t;
SELECT BITMAP_UNION_INT(i) FROM (SELECT 1 AS i UNION ALL SELECT 2 AS i) t;
SELECT BITMAP_UNION_COUNT(BITMAP) FROM (SELECT BITMAP_HASH('ABC') AS BITMAP UNION ALL SELECT BITMAP_HASH('ABC') AS BITMAP) t;
SELECT INTERSECT_COUNT(UID, PAGE, 'MEITUAN'), INTERSECT_COUNT(UID, PAGE, 'WAIMAI') FROM ( SELECT TO_BITMAP(1) AS UID, 'MEITUAN' AS PAGE UNION ALL  SELECT TO_BITMAP(2) AS UID, 'MEITUAN' AS PAGE  UNION ALL SELECT TO_BITMAP(1) AS UID, 'WAIMAI' AS PAGE )PAGE_V